### ISSUE TITLE
Great plugin

### ISSUE THREAD

**Issue by delphinas** [isaactopo/xmlsitemap#1]
How to make it so that sitemaps for multilanguage websites are located in their respective slug? For example, www.website.com/de/sitemap_de.xml rather than all of the sitemaps within www.website.com/sitemap_en and www.website.com/sitemap_de ?

**Comment by isaactopo** [comment]
You can do this modifying the pattern on the plugin `index.php` and changing the `sitemapindex.php` urls for every language-specific sitemap
