### ISSUE TITLE
include unlisted

### ISSUE THREAD

**Issue by kosmar** [isaactopo/xmlsitemap#2]
thanks!

how can i include unlisted pages under a specific slug?

**Comment by isaactopo** [comment]
Hi @kosmar, 
you can include as many pages as you want with the [addCollection option](https://github.com/isaactopo/xmlsitemap#-include-specific-pages).
Something like (not tested):

```php
'isaactopo.xmlsitemap.addCollection' => function () {
    $unlistedPages = page('unlisted-page')->children();
    return $unlistedPages;
},

```

**Comment by kosmar** [comment]
great thx
